import pandas as pd
# personel_list={'isim': ['Ahmet', 'Mehmet', 'Ayşe', 'Fatma','Ali'], 'yaş': [25, 30, 28, 35, 40], 'maaş': [5000, 6000, 5500, 7000, 8000]}
# print(type(personel_list))
# df=pd.DataFrame(personel_list)
# print(type(df))
# print(df)
df=pd.read_excel("personel_list.xlsx")
# print(df)
# print(df.head())
# print(df.head(3))
# print(df.columns)
# print(df.describe())
#print(df.info())
# print(df.dtypes)
# print(df.tail(3))
# print(df.shape)
# print(df[df['maas']>6000])
# print(df.sum())
print(df['maas'].sum())